// <auto-generated />
namespace BioscoopSysteemTouch.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Database_update_04032015_1601 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_update_04032015_1601));
        
        string IMigrationMetadata.Id
        {
            get { return "201503041501570_Database_update_04032015_1601"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
